# Generated by Django 5.1.1 on 2024-10-26 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_status', models.CharField(default='pending', max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Login_or_Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(default='bill-name', max_length=100)),
                ('amount', models.FloatField()),
                ('split_type', models.CharField(default='EQUAL', max_length=50)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('group_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='expense_tracking_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='Group_membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracking_app.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracking_app.login_or_signup')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expense_tracking_app.group')),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='expense_tracking_app.login_or_signup')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='expense_tracking_app.login_or_signup')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracking_app.login_or_signup')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('split_type', models.CharField(default='EQUAL', max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracking_app.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracking_app.login_or_signup')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracking_app.vender')),
            ],
        ),
    ]
